-- Insert sample group tours
INSERT INTO group_tours (
  title, description, destination, category_id, start_date, end_date, duration, 
  price, original_price, max_participants, available_spots, difficulty_level, 
  group_type, image_url, highlights, inclusions, exclusions, itinerary, badges, 
  rating, reviews_count, status, featured, early_bird_discount, is_eco_friendly
) VALUES 
(
  'Incredible India Golden Triangle',
  'Experience the magical Golden Triangle covering Delhi, Agra, and Jaipur. This classic tour showcases India''s rich heritage, magnificent monuments, and vibrant culture.',
  'Delhi, Agra, Jaipur',
  (SELECT id FROM group_tour_categories WHERE name = 'Cultural Tours'),
  '2024-03-15',
  '2024-03-22',
  '8 Days / 7 Nights',
  45000,
  50000,
  25,
  8,
  'Easy',
  'Mixed',
  '/places/china/beijing.jpg',
  ARRAY['Taj Mahal at Sunrise', 'Red Fort Delhi', 'Hawa Mahal Jaipur', 'City Palace', 'Local Cuisine Tasting', 'Traditional Markets'],
  ARRAY['7 Nights Accommodation', 'Daily Breakfast', 'Private Transportation', 'English Speaking Guide', 'All Monument Entries', 'Airport Transfers'],
  ARRAY['International Flights', 'Lunch & Dinner', 'Personal Expenses', 'Tips & Gratuities', 'Travel Insurance'],
  '[
    {"day": 1, "title": "Arrival in Delhi", "description": "Welcome to India! Transfer to hotel and rest.", "activities": ["Airport pickup", "Hotel check-in", "Welcome dinner"]},
    {"day": 2, "title": "Old & New Delhi Tour", "description": "Explore the contrasts of India''s capital.", "activities": ["Red Fort", "Jama Masjid", "India Gate", "Raj Ghat"]},
    {"day": 3, "title": "Delhi to Agra", "description": "Journey to the city of the Taj Mahal.", "activities": ["Drive to Agra", "Agra Fort visit", "Local market exploration"]},
    {"day": 4, "title": "Taj Mahal Sunrise", "description": "Witness the Taj Mahal at sunrise.", "activities": ["Sunrise at Taj Mahal", "Mehtab Bagh gardens", "Marble inlay workshop"]},
    {"day": 5, "title": "Agra to Jaipur", "description": "Travel to the Pink City with Fatehpur Sikri stop.", "activities": ["Fatehpur Sikri", "Drive to Jaipur", "Evening at leisure"]},
    {"day": 6, "title": "Jaipur Sightseeing", "description": "Explore the royal heritage of Rajasthan.", "activities": ["Amber Fort", "City Palace", "Hawa Mahal", "Jantar Mantar"]},
    {"day": 7, "title": "Jaipur to Delhi", "description": "Return to Delhi with shopping time.", "activities": ["Morning at leisure", "Drive to Delhi", "Shopping at Connaught Place"]},
    {"day": 8, "title": "Departure", "description": "Transfer to airport for onward journey.", "activities": ["Hotel checkout", "Airport transfer", "Departure"]}
  ]'::jsonb,
  ARRAY['Top Rated', 'Cultural Heritage'],
  4.8,
  156,
  'Active',
  true,
  10,
  false
),
(
  'Bali Paradise Adventure',
  'Discover the enchanting beauty of Bali with its pristine beaches, ancient temples, lush rice terraces, and vibrant culture. Perfect for adventure seekers and culture enthusiasts.',
  'Ubud, Kuta, Seminyak, Sanur',
  (SELECT id FROM group_tour_categories WHERE name = 'Beach & Islands'),
  '2024-03-25',
  '2024-04-01',
  '7 Days / 6 Nights',
  55000,
  65000,
  18,
  5,
  'Moderate',
  'Adventure Seekers',
  '/places/indonesia/bali.jpg',
  ARRAY['Tegallalang Rice Terraces', 'Temple Hopping', 'Beach Activities', 'Traditional Villages', 'Volcano Trekking', 'Balinese Cooking Class'],
  ARRAY['6 Nights Accommodation', 'Daily Breakfast', 'Airport Transfers', 'Local Transportation', 'English Speaking Guide', 'Temple Entrance Fees'],
  ARRAY['International Flights', 'Lunch & Dinner', 'Personal Expenses', 'Spa Treatments', 'Optional Activities'],
  '[
    {"day": 1, "title": "Arrival in Bali", "description": "Welcome to the Island of Gods!", "activities": ["Airport pickup", "Hotel check-in", "Welcome dinner with traditional dance"]},
    {"day": 2, "title": "Ubud Cultural Tour", "description": "Explore the cultural heart of Bali.", "activities": ["Tegallalang Rice Terraces", "Monkey Forest Sanctuary", "Traditional art villages", "Ubud Palace"]},
    {"day": 3, "title": "Temple Trail", "description": "Visit iconic Balinese temples.", "activities": ["Besakih Temple", "Lempuyang Temple", "Tirta Gangga Water Palace"]},
    {"day": 4, "title": "Volcano Adventure", "description": "Early morning volcano trekking.", "activities": ["Mount Batur sunrise trek", "Natural hot springs", "Coffee plantation visit"]},
    {"day": 5, "title": "Beach Day Seminyak", "description": "Relax at beautiful beaches.", "activities": ["Beach activities", "Water sports", "Sunset at Tanah Lot", "Beach club experience"]},
    {"day": 6, "title": "Cultural Workshop", "description": "Learn traditional Balinese arts.", "activities": ["Cooking class", "Silver jewelry making", "Traditional massage", "Local market visit"]},
    {"day": 7, "title": "Departure", "description": "Last-minute shopping and departure.", "activities": ["Morning at leisure", "Souvenir shopping", "Airport transfer"]}
  ]'::jsonb,
  ARRAY['Early Bird', 'Adventure'],
  4.7,
  89,
  'Active',
  true,
  15,
  true
),
(
  'Dubai Luxury Escape',
  'Experience the epitome of luxury in Dubai and Abu Dhabi. From towering skyscrapers to golden deserts, this tour offers the perfect blend of modern marvels and traditional charm.',
  'Dubai, Abu Dhabi',
  (SELECT id FROM group_tour_categories WHERE name = 'Luxury Tours'),
  '2024-04-05',
  '2024-04-10',
  '6 Days / 5 Nights',
  85000,
  95000,
  15,
  3,
  'Easy',
  'Families',
  '/places/uae/burj-khalifa.jpg',
  ARRAY['Burj Khalifa Sky Deck', 'Desert Safari with BBQ', 'Sheikh Zayed Grand Mosque', 'Dubai Mall & Fountain Show', 'Luxury Shopping', 'Marina Cruise'],
  ARRAY['5 Nights 5-Star Accommodation', 'Daily Breakfast', 'Luxury Transportation', 'Private Guide', 'All Attraction Tickets', 'Desert Safari'],
  ARRAY['International Flights', 'Lunch & Dinner', 'Personal Shopping', 'Spa Treatments', 'Optional Tours'],
  '[
    {"day": 1, "title": "Dubai Arrival", "description": "Luxury welcome to Dubai.", "activities": ["Airport pickup in luxury vehicle", "5-star hotel check-in", "Dubai Marina walk"]},
    {"day": 2, "title": "Modern Dubai", "description": "Explore Dubai''s architectural marvels.", "activities": ["Burj Khalifa visit", "Dubai Mall", "Fountain show", "Gold & Spice Souks"]},
    {"day": 3, "title": "Desert Adventure", "description": "Authentic desert experience.", "activities": ["Desert safari", "Camel riding", "Falconry show", "BBQ dinner under stars"]},
    {"day": 4, "title": "Abu Dhabi Day Trip", "description": "Capital city exploration.", "activities": ["Sheikh Zayed Grand Mosque", "Louvre Abu Dhabi", "Emirates Palace", "Corniche walk"]},
    {"day": 5, "title": "Luxury & Leisure", "description": "Shopping and relaxation.", "activities": ["Mall of Emirates", "Ski Dubai", "Palm Jumeirah", "Atlantis visit"]},
    {"day": 6, "title": "Farewell Dubai", "description": "Last moments in luxury.", "activities": ["Morning at leisure", "Last-minute shopping", "Airport transfer"]}
  ]'::jsonb,
  ARRAY['Luxury', 'Family Friendly'],
  4.9,
  67,
  'Active',
  false,
  0,
  false
),
(
  'Thailand Island Hopping',
  'Explore the tropical paradise of Thailand with its stunning islands, crystal-clear waters, vibrant street food, and warm hospitality. Perfect for beach lovers and culture enthusiasts.',
  'Bangkok, Phuket, Krabi, Phi Phi',
  (SELECT id FROM group_tour_categories WHERE name = 'Beach & Islands'),
  '2024-05-12',
  '2024-05-20',
  '9 Days / 8 Nights',
  48000,
  55000,
  22,
  15,
  'Easy',
  'Solo Travelers',
  '/places/thailand/phuket.jpg',
  ARRAY['Phi Phi Islands', 'James Bond Island', 'Floating Markets', 'Thai Cooking Class', 'Snorkeling', 'Street Food Tours'],
  ARRAY['8 Nights Accommodation', 'Daily Breakfast', 'Inter-island Transfers', 'Boat Tours', 'English Guide', 'Airport Transfers'],
  ARRAY['International Flights', 'Lunch & Dinner', 'Personal Expenses', 'Optional Activities', 'Travel Insurance'],
  '[
    {"day": 1, "title": "Bangkok Arrival", "description": "Welcome to the Land of Smiles!", "activities": ["Airport pickup", "Hotel check-in", "Welcome dinner cruise"]},
    {"day": 2, "title": "Bangkok Temples", "description": "Explore iconic temples and culture.", "activities": ["Grand Palace", "Wat Pho Temple", "Wat Arun", "Floating market"]},
    {"day": 3, "title": "Fly to Phuket", "description": "Begin island adventure.", "activities": ["Morning flight to Phuket", "Beach time", "Old Phuket Town", "Night market"]},
    {"day": 4, "title": "Phi Phi Islands", "description": "Famous island paradise.", "activities": ["Phi Phi Don & Phi Phi Leh", "Maya Bay", "Snorkeling", "Beach relaxation"]},
    {"day": 5, "title": "James Bond Island", "description": "Phang Nga Bay adventure.", "activities": ["James Bond Island", "Sea canoeing", "Floating village", "Cave exploration"]},
    {"day": 6, "title": "Krabi Transfer", "description": "Move to Krabi province.", "activities": ["Transfer to Krabi", "Ao Nang Beach", "Rock climbing (optional)", "Sunset viewing"]},
    {"day": 7, "title": "4 Islands Tour", "description": "Island hopping adventure.", "activities": ["Railay Beach", "Chicken Island", "Poda Island", "Tub Island"]},
    {"day": 8, "title": "Cooking & Culture", "description": "Learn Thai traditions.", "activities": ["Thai cooking class", "Local market visit", "Traditional massage", "Free time"]},
    {"day": 9, "title": "Departure", "description": "Farewell Thailand.", "activities": ["Morning at leisure", "Airport transfer", "Departure"]}
  ]'::jsonb,
  ARRAY['Island Paradise', 'Cultural'],
  4.6,
  134,
  'Active',
  false,
  12,
  true
),
(
  'Switzerland Alpine Adventure',
  'Experience the breathtaking beauty of the Swiss Alps with scenic train rides, pristine lakes, and charming mountain villages. A perfect blend of adventure and relaxation.',
  'Zurich, Interlaken, Zermatt, Lucerne',
  (SELECT id FROM group_tour_categories WHERE name = 'Adventure & Trekking'),
  '2024-06-08',
  '2024-06-16',
  '9 Days / 8 Nights',
  125000,
  140000,
  16,
  9,
  'Moderate',
  'Adventure Seekers',
  '/places/europe/alps.jpg',
  ARRAY['Matterhorn Views', 'Jungfraujoch Top of Europe', 'Lake Geneva', 'Rhine Falls', 'Alpine Train Rides', 'Mountain Hiking'],
  ARRAY['8 Nights Accommodation', 'Daily Breakfast', 'Swiss Pass', 'All Train Journeys', 'Cable Car Rides', 'English Guide'],
  ARRAY['International Flights', 'Lunch & Dinner', 'Personal Expenses', 'Optional Activities', 'Travel Insurance'],
  '[
    {"day": 1, "title": "Zurich Arrival", "description": "Welcome to Switzerland!", "activities": ["Airport pickup", "Zurich old town", "Lake Zurich walk", "Welcome dinner"]},
    {"day": 2, "title": "Rhine Falls & Lucerne", "description": "Waterfalls and lake city.", "activities": ["Rhine Falls visit", "Train to Lucerne", "Chapel Bridge", "Mount Pilatus cable car"]},
    {"day": 3, "title": "Interlaken Journey", "description": "Gateway to the Alps.", "activities": ["Scenic train to Interlaken", "Lake Thun cruise", "Adventure activities", "Alpine views"]},
    {"day": 4, "title": "Jungfraujoch", "description": "Top of Europe experience.", "activities": ["Jungfraujoch railway", "Ice Palace", "Sphinx Observatory", "Alpine hiking"]},
    {"day": 5, "title": "Zermatt & Matterhorn", "description": "Iconic Swiss peak.", "activities": ["Train to Zermatt", "Gornergrat railway", "Matterhorn views", "Village exploration"]},
    {"day": 6, "title": "Mountain Adventures", "description": "Alpine activities day.", "activities": ["Cable car rides", "Mountain hiking", "Alpine lakes", "Traditional lunch"]},
    {"day": 7, "title": "Lake Geneva Region", "description": "Swiss Riviera experience.", "activities": ["Train to Montreux", "Chillon Castle", "Lavaux vineyards", "Lake cruise"]},
    {"day": 8, "title": "Return to Zurich", "description": "Final Swiss experiences.", "activities": ["Morning in Geneva region", "Return to Zurich", "Shopping time", "Farewell dinner"]},
    {"day": 9, "title": "Departure", "description": "Goodbye Switzerland.", "activities": ["Morning at leisure", "Airport transfer", "Departure"]}
  ]'::jsonb,
  ARRAY['Top Rated', 'Alpine Adventure'],
  4.9,
  78,
  'Active',
  true,
  8,
  true
),
(
  'Morocco Desert Expedition',
  'Journey through Morocco''s imperial cities, Atlas Mountains, and the magical Sahara Desert. Experience the rich culture, stunning architecture, and desert adventures.',
  'Marrakech, Fes, Sahara Desert, Casablanca',
  (SELECT id FROM group_tour_categories WHERE name = 'Adventure & Trekking'),
  '2024-04-20',
  '2024-04-28',
  '9 Days / 8 Nights',
  67000,
  75000,
  20,
  12,
  'Challenging',
  'Adventure Seekers',
  '/places/africa-1.jpg',
  ARRAY['Sahara Desert Camping', 'Atlas Mountains', 'Imperial Cities', 'Camel Trekking', 'Berber Villages', 'Traditional Souks'],
  ARRAY['8 Nights Accommodation', 'Desert Camp', 'Daily Breakfast', 'Transportation', 'Camel Trek', 'Local Guide'],
  ARRAY['International Flights', 'Lunch & Dinner', 'Personal Expenses', 'Tips', 'Optional Activities'],
  '[
    {"day": 1, "title": "Marrakech Arrival", "description": "Welcome to Morocco!", "activities": ["Airport pickup", "Riad check-in", "Djemaa el-Fna square", "Welcome dinner"]},
    {"day": 2, "title": "Marrakech Discovery", "description": "Red City exploration.", "activities": ["Bahia Palace", "Saadian Tombs", "Majorelle Gardens", "Souks tour"]},
    {"day": 3, "title": "Atlas Mountains", "description": "Mountain Berber villages.", "activities": ["Drive through Atlas", "Berber villages", "Traditional lunch", "Mountain hiking"]},
    {"day": 4, "title": "Desert Journey", "description": "Towards the Sahara.", "activities": ["Drive to Merzouga", "Camel trekking", "Desert camp", "Sunset in dunes"]},
    {"day": 5, "title": "Sahara Experience", "description": "Full desert immersion.", "activities": ["Sunrise camel ride", "Desert activities", "Nomad encounters", "Star gazing"]},
    {"day": 6, "title": "Fes Journey", "description": "Imperial city bound.", "activities": ["Drive to Fes", "Cedar forests", "Ifrane town", "Medina evening walk"]},
    {"day": 7, "title": "Fes Medina", "description": "Ancient city exploration.", "activities": ["Fes Medina tour", "Tanneries visit", "Al Quaraouiyine", "Traditional crafts"]},
    {"day": 8, "title": "Casablanca", "description": "Modern Morocco.", "activities": ["Drive to Casablanca", "Hassan II Mosque", "Corniche walk", "Farewell dinner"]},
    {"day": 9, "title": "Departure", "description": "Au revoir Morocco!", "activities": ["Morning at leisure", "Airport transfer", "Departure"]}
  ]'::jsonb,
  ARRAY['Desert Adventure', 'Cultural'],
  4.7,
  92,
  'Active',
  false,
  0,
  false
);

-- Insert some sample reviews
INSERT INTO tour_reviews (tour_id, reviewer_name, reviewer_image, rating, review_text, is_verified, social_media_link) VALUES
((SELECT id FROM group_tours WHERE title = 'Incredible India Golden Triangle'), 'Sarah Johnson', null, 5, 'Absolutely amazing experience! The Taj Mahal at sunrise was breathtaking. Our guide was knowledgeable and the group was fantastic. Highly recommend!', true, 'https://instagram.com/sarahtravels'),
((SELECT id FROM group_tours WHERE title = 'Incredible India Golden Triangle'), 'Michael Chen', null, 5, 'Perfect introduction to India. Well organized, great accommodations, and incredible sights. The group size was just right.', true, null),
((SELECT id FROM group_tours WHERE title = 'Bali Paradise Adventure'), 'Emma Rodriguez', null, 5, 'Bali exceeded all expectations! The volcano trek was challenging but so rewarding. Loved the cooking class and the beaches were pristine.', true, 'https://instagram.com/emmaadventures'),
((SELECT id FROM group_tours WHERE title = 'Dubai Luxury Escape'), 'James Wilson', null, 4, 'Luxury at its finest! Dubai is incredible and the desert safari was unforgettable. Only wish we had more time in Abu Dhabi.', true, null),
((SELECT id FROM group_tours WHERE title = 'Thailand Island Hopping'), 'Lisa Park', null, 5, 'Island paradise indeed! Phi Phi was stunning and the group bonded really well. Thai food is amazing and the people are so friendly.', true, 'https://instagram.com/lisaexplores'),
((SELECT id FROM group_tours WHERE title = 'Switzerland Alpine Adventure'), 'David Kumar', null, 5, 'Switzerland is pure magic! The train rides were scenic, Matterhorn views were spectacular. Expensive but totally worth every penny.', true, null);