-- Insert comprehensive SEO settings for all pages
INSERT INTO public.seo_settings (page_url, meta_title, meta_description, meta_keywords, canonical_url, og_title, og_description, og_image, page_type, robots_meta, structured_data, is_active)
VALUES 
-- Homepage
('/', 'Nymphette Tours - Premium Travel Packages & Group Tours Worldwide', 'Discover amazing travel destinations with Nymphette Tours. Expert-curated packages, group tours, and personalized travel experiences across Asia, Europe, Americas & more.', 'travel packages, group tours, vacation planning, nymphette tours, asia travel, europe travel, travel agency', 'https://nymphettetours.com/', 'Nymphette Tours - Your Gateway to World Adventures', 'Experience the world with our premium travel packages and expert-guided group tours. From Asia to Europe, create unforgettable memories.', '/og-homepage.jpg', 'homepage', 'index,follow', '{"@context":"https://schema.org","@type":"WebSite","name":"Nymphette Tours","url":"https://nymphettetours.com","potentialAction":{"@type":"SearchAction","target":"https://nymphettetours.com/?search={search_term_string}","query-input":"required name=search_term_string"}}', true),

-- Packages Page
('/packages', 'Travel Packages - Curated Tours & Vacation Deals | Nymphette Tours', 'Browse our collection of premium travel packages featuring destinations across Asia, Europe, and beyond. Expert-planned itineraries with competitive pricing.', 'travel packages, vacation deals, tour packages, asia packages, europe packages, holiday packages, travel deals', 'https://nymphettetours.com/packages', 'Premium Travel Packages Worldwide - Nymphette Tours', 'Discover our handpicked travel packages designed for unforgettable experiences. From cultural tours to adventure packages.', '/og-packages.jpg', 'packages', 'index,follow', '{"@context":"https://schema.org","@type":"WebPage","name":"Travel Packages","description":"Premium travel packages and vacation deals","mainEntity":{"@type":"ItemList","name":"Travel Packages","numberOfItems":50}}', true),

-- Group Tours Page
('/group-tours', 'Group Tours - Small Group Adventures & Guided Tours | Nymphette Tours', 'Join our small group tours for intimate travel experiences. Expert guides, carefully planned itineraries, and like-minded travelers worldwide.', 'group tours, small group travel, guided tours, adventure tours, cultural tours, group travel', 'https://nymphettetours.com/group-tours', 'Small Group Adventures - Guided Tours Worldwide', 'Travel with like-minded adventurers on our expertly guided small group tours. Authentic experiences, local insights.', '/og-group-tours.jpg', 'group-tours', 'index,follow', '{"@context":"https://schema.org","@type":"WebPage","name":"Group Tours","description":"Small group tours and guided adventures","mainEntity":{"@type":"ItemList","name":"Group Tours"}}', true),

-- Blog Page
('/blog', 'Travel Blog - Destination Guides & Travel Tips | Nymphette Tours', 'Get inspired with our travel blog featuring destination guides, travel tips, cultural insights, and stories from around the world.', 'travel blog, destination guides, travel tips, travel stories, vacation inspiration, cultural insights', 'https://nymphettetours.com/blog', 'Travel Inspiration & Destination Guides', 'Discover amazing destinations, get travel tips, and read inspiring stories from fellow travelers and our expert guides.', '/og-blog.jpg', 'blog', 'index,follow', '{"@context":"https://schema.org","@type":"Blog","name":"Nymphette Tours Travel Blog","publisher":{"@type":"Organization","name":"Nymphette Tours"}}', true),

-- About Page
('/about', 'About Nymphette Tours - Premium Travel Company Since 2010', 'Learn about Nymphette Tours, your trusted travel partner. Our story, mission, and commitment to creating extraordinary travel experiences worldwide.', 'about nymphette tours, travel company, tour operator, travel agency, our story, travel expertise', 'https://nymphettetours.com/about', 'About Nymphette Tours - Your Trusted Travel Partner', 'Discover our passion for travel and commitment to creating exceptional experiences. Learn about our team and travel philosophy.', '/og-about.jpg', 'about', 'index,follow', '{"@context":"https://schema.org","@type":"AboutPage","name":"About Nymphette Tours","mainEntity":{"@type":"Organization","name":"Nymphette Tours","foundingDate":"2010"}}', true),

-- Contact Page
('/contact', 'Contact Us - Book Your Dream Vacation | Nymphette Tours', 'Ready to plan your next adventure? Contact our travel experts for personalized trip planning, booking assistance, and travel advice.', 'contact travel agency, book tour, travel inquiry, trip planning, travel consultation, nymphette contact', 'https://nymphettetours.com/contact', 'Contact Nymphette Tours - Plan Your Next Adventure', 'Get in touch with our travel experts for personalized trip planning and booking assistance. We are here to help!', '/og-contact.jpg', 'contact', 'index,follow', '{"@context":"https://schema.org","@type":"ContactPage","name":"Contact Nymphette Tours"}', true),

-- Asia Region
('/regions/asia', 'Asia Travel Packages - Southeast Asia Tours | Nymphette Tours', 'Explore Asia with our comprehensive travel packages. From bustling cities to serene temples, discover the magic of Southeast Asia and beyond.', 'asia travel, southeast asia tours, asia vacation, asian destinations, thailand tours, japan tours, indonesia tours', 'https://nymphettetours.com/regions/asia', 'Discover Asia - Premium Travel Packages', 'Experience the diversity of Asia with our expert-curated travel packages. From cultural wonders to natural beauty.', '/og-asia.jpg', 'custom', 'index,follow', '{"@context":"https://schema.org","@type":"WebPage","name":"Asia Travel Packages","about":{"@type":"Place","name":"Asia"}}', true),

-- Europe Region
('/regions/europe', 'Europe Travel Packages - European Tours & Vacations | Nymphette Tours', 'Discover Europe with our premium travel packages. From historic cities to stunning landscapes, experience the best of European culture and beauty.', 'europe travel, european tours, europe vacation, european packages, france tours, italy tours, spain tours', 'https://nymphettetours.com/regions/europe', 'European Adventures - Premium Travel Packages', 'Explore Europe rich history, culture, and landscapes with our carefully crafted travel packages and expert guides.', '/og-europe.jpg', 'custom', 'index,follow', '{"@context":"https://schema.org","@type":"WebPage","name":"Europe Travel Packages","about":{"@type":"Place","name":"Europe"}}', true);