-- Insert 25 packages (5 per region) across 5 different regions

-- Asia Packages (5)
INSERT INTO packages (title, country, country_slug, region, duration, price, original_price, rating, reviews, image, highlights, inclusions, exclusions, category, best_time, group_size, featured, overview_description, itinerary) VALUES
('Tokyo Cherry Blossom Tour', 'Japan', 'japan', 'Asia', '7D/6N', '₹85,000', '₹95,000', 4.8, 127, '/places/japan/tokyo.jpg', ARRAY['Cherry Blossoms', 'Traditional Culture', 'Modern Cities'], ARRAY['Accommodation', 'Daily Breakfast', 'Airport Transfers', 'Guided Tours'], ARRAY['International Flights', 'Lunch & Dinner', 'Personal Expenses'], 'Cultural', 'March - May', '2-15 people', true, 'Experience the magical cherry blossom season in Japan with traditional temples, modern cities, and cultural immersion.', '[{"day": 1, "title": "Arrival in Tokyo", "description": "Welcome to Tokyo", "activities": ["Airport pickup", "Hotel check-in", "Welcome dinner"], "meals": ["Dinner"]}]'),
('Thai Beach Paradise', 'Thailand', 'thailand', 'Asia', '6D/5N', '₹45,000', '₹55,000', 4.7, 203, '/places/thailand/phuket.jpg', ARRAY['Beach Resorts', 'Island Hopping', 'Thai Cuisine'], ARRAY['Beach Resort Stay', 'Island Tours', 'Thai Cooking Class', 'Airport Transfers'], ARRAY['International Flights', 'Alcoholic Beverages', 'Spa Treatments'], 'Beach', 'November - March', '2-20 people', true, 'Relax on pristine beaches of Thailand with island hopping and authentic Thai experiences.', '[{"day": 1, "title": "Arrival in Phuket", "description": "Beach paradise begins", "activities": ["Airport transfer", "Beach resort check-in", "Sunset viewing"], "meals": ["Welcome drink"]}]'),
('Bali Cultural Experience', 'Indonesia', 'indonesia', 'Asia', '8D/7N', '₹52,000', '₹62,000', 4.6, 189, '/places/indonesia/bali.jpg', ARRAY['Rice Terraces', 'Hindu Temples', 'Volcanic Landscapes'], ARRAY['Accommodation', 'Temple Tours', 'Rice Terrace Trek', 'Cultural Shows'], ARRAY['International Flights', 'Personal Shopping', 'Optional Activities'], 'Cultural', 'April - October', '2-18 people', false, 'Discover the spiritual and cultural heart of Bali with temple visits, rice terraces, and traditional arts.', '[{"day": 1, "title": "Arrival in Denpasar", "description": "Welcome to Bali", "activities": ["Airport pickup", "Hotel check-in", "Traditional welcome ceremony"], "meals": ["Welcome dinner"]}]'),
('Singapore City Break', 'Singapore', 'singapore', 'Asia', '4D/3N', '₹38,000', '₹45,000', 4.5, 156, '/places/singapore/singapore.jpg', ARRAY['Modern Architecture', 'Street Food', 'Gardens by the Bay'], ARRAY['City Hotel', 'City Tours', 'Marina Bay Tour', 'Food Tour'], ARRAY['International Flights', 'Shopping', 'Additional Meals'], 'City', 'Year Round', '2-12 people', false, 'Explore the futuristic city-state of Singapore with its iconic skyline, gardens, and diverse cuisine.', '[{"day": 1, "title": "Arrival in Singapore", "description": "City exploration begins", "activities": ["Airport transfer", "Marina Bay visit", "Night safari"], "meals": ["Dinner"]}]'),
('Vietnam Adventure', 'Vietnam', 'vietnam', 'Asia', '9D/8N', '₹55,000', '₹65,000', 4.4, 142, '/places/vietnam/ho-chi-minh.jpg', ARRAY['Ha Long Bay', 'Street Food', 'French Colonial'], ARRAY['Accommodation', 'Ha Long Bay Cruise', 'City Tours', 'Cooking Class'], ARRAY['International Flights', 'Personal Expenses', 'Optional Excursions'], 'Adventure', 'October - April', '2-16 people', false, 'Adventure through Vietnam from bustling Ho Chi Minh City to the stunning Ha Long Bay.', '[{"day": 1, "title": "Arrival in Ho Chi Minh City", "description": "Vietnam adventure begins", "activities": ["Airport pickup", "City orientation tour", "Street food exploration"], "meals": ["Street food dinner"]}]'),

-- Europe Packages (5)
('European Grand Tour', 'France', 'france', 'Europe', '12D/11N', '₹1,25,000', '₹1,45,000', 4.9, 298, '/assets/countries/france.jpg', ARRAY['Historic Cities', 'Art Museums', 'Fine Dining'], ARRAY['Luxury Hotels', 'Guided Tours', 'Museum Entries', 'High-speed Rail'], ARRAY['International Flights', 'Lunch & Dinner', 'Personal Shopping'], 'Luxury', 'April - October', '2-25 people', true, 'Experience the best of Europe with Paris, Rome, and Swiss Alps in one magnificent journey.', '[{"day": 1, "title": "Arrival in Paris", "description": "City of Light welcomes you", "activities": ["Airport transfer", "Eiffel Tower visit", "Seine river cruise"], "meals": ["Welcome dinner"]}]'),
('Italian Romance', 'Italy', 'italy', 'Europe', '10D/9N', '₹95,000', '₹1,15,000', 4.8, 245, '/assets/countries/italy.jpg', ARRAY['Renaissance Art', 'Tuscan Countryside', 'Authentic Cuisine'], ARRAY['Boutique Hotels', 'Art Tours', 'Wine Tasting', 'Cooking Classes'], ARRAY['International Flights', 'Some Meals', 'Personal Expenses'], 'Romance', 'May - September', '2-20 people', true, 'Fall in love with Italy through Renaissance art, Tuscan wines, and romantic cities.', '[{"day": 1, "title": "Arrival in Rome", "description": "Eternal City awaits", "activities": ["Airport transfer", "Colosseum visit", "Roman forum tour"], "meals": ["Traditional Italian dinner"]}]'),
('Swiss Alpine Adventure', 'Switzerland', 'switzerland', 'Europe', '8D/7N', '₹1,05,000', '₹1,25,000', 4.7, 178, '/assets/europe/alps.jpg', ARRAY['Snow-capped Peaks', 'Mountain Railways', 'Alpine Villages'], ARRAY['Mountain Hotels', 'Cable Car Rides', 'Alpine Tours', 'Traditional Meals'], ARRAY['International Flights', 'Additional Activities', 'Personal Shopping'], 'Adventure', 'June - September', '2-15 people', false, 'Breathtaking Swiss Alps with scenic railways, pristine lakes, and charming alpine villages.', '[{"day": 1, "title": "Arrival in Zurich", "description": "Alpine adventure begins", "activities": ["Airport transfer", "Lake Zurich boat trip", "Old town walking tour"], "meals": ["Swiss fondue dinner"]}]'),
('Greek Island Hopping', 'Greece', 'greece', 'Europe', '9D/8N', '₹78,000', '₹88,000', 4.6, 167, '/assets/europe/santorini.jpg', ARRAY['Ancient Ruins', 'Blue & White Architecture', 'Mediterranean Cuisine'], ARRAY['Island Hotels', 'Ferry Transfers', 'Archaeological Tours', 'Sunset Views'], ARRAY['International Flights', 'Some Meals', 'Optional Tours'], 'Island', 'April - October', '2-18 people', false, 'Discover the beauty of Greek islands with ancient history, stunning sunsets, and Mediterranean charm.', '[{"day": 1, "title": "Arrival in Athens", "description": "Ancient Greece exploration", "activities": ["Airport transfer", "Acropolis visit", "Greek cuisine tasting"], "meals": ["Traditional Greek dinner"]}]'),
('Spanish Culture Tour', 'Spain', 'spain', 'Europe', '7D/6N', '₹65,000', '₹75,000', 4.5, 134, '/assets/countries/spain.jpg', ARRAY['Flamenco Dancing', 'Gothic Architecture', 'Tapas Culture'], ARRAY['City Hotels', 'Flamenco Shows', 'Architectural Tours', 'Tapas Tours'], ARRAY['International Flights', 'Additional Meals', 'Personal Expenses'], 'Cultural', 'March - November', '2-22 people', false, 'Immerse in Spanish culture with flamenco, architecture, and culinary delights from Madrid to Barcelona.', '[{"day": 1, "title": "Arrival in Madrid", "description": "Spanish culture immersion", "activities": ["Airport transfer", "Prado Museum", "Tapas walking tour"], "meals": ["Tapas dinner"]}]'),

-- Africa Packages (5)
('Kenya Safari Adventure', 'Kenya', 'kenya', 'Africa', '8D/7N', '₹1,15,000', '₹1,35,000', 4.8, 189, '/places/kenya/masai-mara.jpg', ARRAY['Big Five Safari', 'Masai Culture', 'Wildlife Migration'], ARRAY['Safari Lodges', 'Game Drives', 'Cultural Visits', 'Park Fees'], ARRAY['International Flights', 'Alcoholic Beverages', 'Personal Items'], 'Safari', 'July - October', '2-12 people', true, 'Witness the Great Migration and Big Five in Kenya''s premier safari destinations.', '[{"day": 1, "title": "Arrival in Nairobi", "description": "Safari adventure begins", "activities": ["Airport transfer", "Nairobi National Park", "Welcome briefing"], "meals": ["Safari dinner"]}]'),
('Morocco Imperial Cities', 'Morocco', 'morocco', 'Africa', '9D/8N', '₹85,000', '₹95,000', 4.6, 156, '/places/morocco/marrakech.jpg', ARRAY['Imperial Cities', 'Desert Safari', 'Traditional Souks'], ARRAY['Riads & Hotels', 'Desert Camp', 'Guided Tours', 'Camel Trekking'], ARRAY['International Flights', 'Some Meals', 'Personal Shopping'], 'Cultural', 'October - April', '2-16 people', true, 'Explore Morocco''s imperial cities, ride camels in the Sahara, and experience authentic Berber culture.', '[{"day": 1, "title": "Arrival in Marrakech", "description": "Imperial cities journey", "activities": ["Airport transfer", "Medina exploration", "Jemaa el-Fnaa square"], "meals": ["Moroccan tagine dinner"]}]'),
('South African Highlights', 'South Africa', 'south-africa', 'Africa', '10D/9N', '₹98,000', '₹1,18,000', 4.7, 167, '/places/south-africa/cape-town.jpg', ARRAY['Table Mountain', 'Wine Regions', 'Penguin Colony'], ARRAY['Hotels & Lodges', 'Wine Tasting', 'City Tours', 'Cable Car Rides'], ARRAY['International Flights', 'Additional Activities', 'Personal Expenses'], 'Adventure', 'November - March', '2-18 people', false, 'Discover South Africa from Cape Town''s beauty to wine regions and wildlife encounters.', '[{"day": 1, "title": "Arrival in Cape Town", "description": "Rainbow nation exploration", "activities": ["Airport transfer", "Table Mountain cable car", "V&A Waterfront"], "meals": ["South African braai dinner"]}]'),
('Tanzania Wildlife Safari', 'Tanzania', 'tanzania', 'Africa', '7D/6N', '₹1,05,000', '₹1,25,000', 4.8, 145, '/places/tanzania/serengeti.jpg', ARRAY['Serengeti Plains', 'Ngorongoro Crater', 'Kilimanjaro Views'], ARRAY['Safari Lodges', 'Game Drives', 'Crater Tours', 'Cultural Visits'], ARRAY['International Flights', 'Beverages', 'Optional Activities'], 'Safari', 'June - October', '2-14 people', false, 'Experience Tanzania''s incredible wildlife in Serengeti and Ngorongoro with views of Kilimanjaro.', '[{"day": 1, "title": "Arrival in Arusha", "description": "Wildlife safari begins", "activities": ["Airport transfer", "Safari briefing", "Local market visit"], "meals": ["Safari camp dinner"]}]'),
('Egyptian Ancient Wonders', 'Egypt', 'egypt', 'Africa', '8D/7N', '₹75,000', '₹85,000', 4.5, 198, '/places/egypt/pyramids.jpg', ARRAY['Pyramids of Giza', 'Nile River Cruise', 'Ancient Temples'], ARRAY['Hotels & Cruise', 'Guided Tours', 'Museum Entries', 'Nile Cruise'], ARRAY['International Flights', 'Optional Tours', 'Personal Shopping'], 'Historical', 'October - April', '2-25 people', false, 'Journey through ancient Egypt with pyramids, Sphinx, Nile cruise, and pharaonic treasures.', '[{"day": 1, "title": "Arrival in Cairo", "description": "Ancient wonders await", "activities": ["Airport transfer", "Pyramids of Giza", "Egyptian Museum"], "meals": ["Egyptian cuisine dinner"]}]'),

-- Americas Packages (5)
('USA Coast to Coast', 'USA', 'usa', 'Americas', '14D/13N', '₹1,85,000', '₹2,15,000', 4.7, 234, '/places/usa/times-square.jpg', ARRAY['New York City', 'Grand Canyon', 'Hollywood'], ARRAY['Hotels', 'Domestic Flights', 'City Tours', 'National Park Entries'], ARRAY['International Flights', 'Most Meals', 'Personal Expenses'], 'City', 'April - October', '2-20 people', true, 'Epic American journey from NYC''s skyline to California''s beaches with iconic landmarks.', '[{"day": 1, "title": "Arrival in New York", "description": "American dream begins", "activities": ["Airport transfer", "Times Square visit", "Empire State Building"], "meals": ["New York deli dinner"]}]'),
('Canada Natural Wonders', 'Canada', 'canada', 'Americas', '10D/9N', '₹1,35,000', '₹1,55,000', 4.6, 187, '/places/canada/niagara.jpg', ARRAY['Niagara Falls', 'Rocky Mountains', 'French Culture'], ARRAY['Hotels', 'Train Journeys', 'National Parks', 'City Tours'], ARRAY['International Flights', 'Some Meals', 'Optional Activities'], 'Nature', 'May - September', '2-18 people', false, 'Explore Canada''s natural beauty from Niagara Falls to Rocky Mountains and charming Quebec.', '[{"day": 1, "title": "Arrival in Toronto", "description": "Canadian adventure starts", "activities": ["Airport transfer", "CN Tower visit", "Harbourfront walk"], "meals": ["Canadian cuisine dinner"]}]'),
('Brazil Carnival & Beaches', 'Brazil', 'brazil', 'Americas', '9D/8N', '₹95,000', '₹1,15,000', 4.8, 176, '/places/brazil/rio.jpg', ARRAY['Carnival Festival', 'Christ the Redeemer', 'Copacabana Beach'], ARRAY['Hotels', 'Carnival Events', 'City Tours', 'Beach Activities'], ARRAY['International Flights', 'Additional Events', 'Personal Expenses'], 'Festival', 'February - March', '2-15 people', true, 'Experience Brazil''s vibrant carnival culture, iconic landmarks, and stunning beaches.', '[{"day": 1, "title": "Arrival in Rio", "description": "Carnival magic begins", "activities": ["Airport transfer", "Sugarloaf Mountain", "Samba show"], "meals": ["Brazilian churrasco"]}]'),
('Peru Machu Picchu Trek', 'Peru', 'peru', 'Americas', '8D/7N', '₹78,000', '₹88,000', 4.9, 298, '/places/peru/machu-picchu.jpg', ARRAY['Machu Picchu', 'Inca Trail', 'Sacred Valley'], ARRAY['Hotels & Lodges', 'Inca Trail Permits', 'Guided Treks', 'Cultural Tours'], ARRAY['International Flights', 'Personal Gear', 'Tips'], 'Adventure', 'May - September', '2-12 people', true, 'Trek the legendary Inca Trail to Machu Picchu and explore Peru''s ancient Incan heritage.', '[{"day": 1, "title": "Arrival in Cusco", "description": "Inca adventure begins", "activities": ["Airport transfer", "Acclimatization walk", "Inca museum"], "meals": ["Peruvian cuisine dinner"]}]'),
('Argentina Wine & Tango', 'Argentina', 'argentina', 'Americas', '7D/6N', '₹85,000', '₹95,000', 4.5, 134, '/places/argentina/buenos-aires.jpg', ARRAY['Tango Shows', 'Wine Regions', 'Steak Culture'], ARRAY['Hotels', 'Wine Tours', 'Tango Lessons', 'City Tours'], ARRAY['International Flights', 'Additional Wine Tastings', 'Personal Shopping'], 'Cultural', 'March - May, Sept - Nov', '2-16 people', false, 'Discover Argentina''s passionate tango culture and world-renowned wine regions.', '[{"day": 1, "title": "Arrival in Buenos Aires", "description": "Tango passion awakens", "activities": ["Airport transfer", "Tango show", "City walking tour"], "meals": ["Argentine steak dinner"]}]'),

-- Pacific Islands Packages (5)
('Maldives Luxury Escape', 'Maldives', 'maldives', 'Pacific Islands', '6D/5N', '₹1,45,000', '₹1,75,000', 4.9, 267, '/places/maldives/overwater-villas.jpg', ARRAY['Overwater Villas', 'Coral Reefs', 'Spa Treatments'], ARRAY['Overwater Villa', 'All Meals', 'Spa Access', 'Water Sports'], ARRAY['International Flights', 'Alcoholic Beverages', 'Excursions'], 'Luxury', 'November - April', '2-4 people', true, 'Ultimate luxury in Maldives with overwater villas, pristine reefs, and world-class spas.', '[{"day": 1, "title": "Arrival in Maldives", "description": "Paradise found", "activities": ["Seaplane transfer", "Villa check-in", "Sunset dolphin cruise"], "meals": ["Beachside dinner"]}]'),
('Fiji Island Paradise', 'Fiji', 'fiji', 'Pacific Islands', '8D/7N', '₹98,000', '₹1,18,000', 4.7, 189, '/places/fiji/island.jpg', ARRAY['Coral Coast', 'Traditional Ceremonies', 'Snorkeling'], ARRAY['Resort Stay', 'Island Tours', 'Cultural Shows', 'Water Activities'], ARRAY['International Flights', 'Some Activities', 'Personal Expenses'], 'Beach', 'May - October', '2-12 people', false, 'Experience Fijian hospitality with pristine beaches, coral reefs, and traditional culture.', '[{"day": 1, "title": "Arrival in Nadi", "description": "Bula! Fiji welcomes", "activities": ["Airport transfer", "Traditional welcome", "Beach relaxation"], "meals": ["Fijian feast"]}]'),
('Hawaii Multi-Island', 'Hawaii', 'hawaii', 'Pacific Islands', '10D/9N', '₹1,65,000', '₹1,95,000', 4.8, 245, '/places/hawaii/maui.jpg', ARRAY['Volcanic Landscapes', 'Hawaiian Culture', 'Tropical Beaches'], ARRAY['Hotels', 'Inter-island Flights', 'Volcano Tours', 'Cultural Experiences'], ARRAY['International Flights', 'Car Rentals', 'Additional Tours'], 'Nature', 'Year Round', '2-15 people', true, 'Explore Hawaii''s diverse islands with volcanoes, beaches, and rich Polynesian culture.', '[{"day": 1, "title": "Arrival in Honolulu", "description": "Aloha spirit begins", "activities": ["Airport transfer", "Pearl Harbor visit", "Waikiki Beach"], "meals": ["Traditional luau"]}]'),
('Tahiti Romance', 'Tahiti', 'tahiti', 'Pacific Islands', '7D/6N', '₹1,25,000', '₹1,45,000', 4.6, 156, '/places/tahiti/bora-bora.jpg', ARRAY['Bora Bora Lagoon', 'Polynesian Culture', 'Black Pearl Farms'], ARRAY['Overwater Bungalows', 'Lagoon Tours', 'Cultural Shows', 'Pearl Farm Visits'], ARRAY['International Flights', 'Additional Excursions', 'Personal Shopping'], 'Romance', 'May - October', '2-8 people', false, 'Romantic escape to Tahiti and Bora Bora with overwater bungalows and stunning lagoons.', '[{"day": 1, "title": "Arrival in Papeete", "description": "Polynesian paradise", "activities": ["Airport transfer", "Market visit", "Sunset cruise"], "meals": ["Polynesian dinner"]}]'),
('Mauritius Tropical Bliss', 'Mauritius', 'mauritius', 'Pacific Islands', '7D/6N', '₹85,000', '₹1,05,000', 4.5, 167, '/places/mauritius/beach.jpg', ARRAY['Pristine Beaches', 'Multicultural Heritage', 'Water Sports'], ARRAY['Beach Resort', 'Island Tours', 'Water Sports', 'Cultural Visits'], ARRAY['International Flights', 'Additional Activities', 'Personal Expenses'], 'Beach', 'April - June, Sept - Dec', '2-14 people', false, 'Discover Mauritius'' pristine beaches, multicultural heritage, and exciting water adventures.', '[{"day": 1, "title": "Arrival in Port Louis", "description": "Tropical paradise awaits", "activities": ["Airport transfer", "Port Louis tour", "Beach relaxation"], "meals": ["Mauritian cuisine dinner"]}]');