// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://duouhbzwivonyssvtiqo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR1b3VoYnp3aXZvbnlzc3Z0aXFvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU1MjkzNjIsImV4cCI6MjA3MTEwNTM2Mn0.PjAbI-RLQpL8_hFr29bWdkrIUAPcPWTHgqJGV9CYyQ0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Create memory storage for SSR
const memoryStorage = {
  data: new Map<string, string>(),
  getItem: (key: string) => memoryStorage.data.get(key) ?? null,
  setItem: (key: string, value: string) => { memoryStorage.data.set(key, value); },
  removeItem: (key: string) => { memoryStorage.data.delete(key); },
};

// Use memory storage for SSR, localStorage for client
const storage = typeof window !== 'undefined' ? localStorage : memoryStorage;

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage,
    persistSession: typeof window !== 'undefined',
    autoRefreshToken: true,
  },
  db: {
    schema: 'public'
  }
});